### ISSUE TITLE
Official CTRE Phoenix 6 

### ISSUE THREAD

**Issue by github3658** [Team364/BaseFalconSwerve#41]
With todays release of CTRE Phoenix 6 officially will you be updating the code base accordingly?

https://www.chiefdelphi.com/t/ctre-2024-phoenix-software-now-available/449023/3

**Comment by rzblue** [comment]
It has been updated for 2024: https://github.com/dirtbikerxz/BaseTalonFXSwerve/commit/da104b5f8a286a0ca86ea2eb3cdabb9d4b2ed6d8
