### ISSUE TITLE
PathPlanner 24 integration

### ISSUE THREAD

**Issue by PlerionPlorion** [Team364/BaseFalconSwerve#59]
Hi! How would I implement the new pathplanner API? It requires methods that don't exist and I'm not sure how to get the relative speeds and set the relative speeds.

**Comment by swalha1999** [comment]
Hey you can take a look at our codebase we have all the methods

**Comment by PlerionPlorion** [comment]
Yes but pathplanner needs a method that gets the relative robot speed and another one that drives the robot based on relative robot speeds, the default set/getModuleStates throw the IDE error: The type Swerve does not define setModuleStates(ChassisSpeeds) that is applicable here

**Comment by swalha1999** [comment]
https://github.com/swalha1999/BaseFalconSwerve
In here we have added the missing method you can take a look

**Comment by PlerionPlorion** [comment]
Thank you! Sorry for not understanding what you meant, I was assuming you meant the main pathplanner repo.
