### ISSUE TITLE
SwerveDriveOdometry is undefined

### ISSUE THREAD

**Issue by WrenVin** [Team364/BaseFalconSwerve#6]
This line: 
swerveOdometry = new SwerveDriveOdometry(Constants.Swerve.swerveKinematics, getYaw());

I am getting a error that SwerveDriveOdometry is undefined. How can I fix this?

**Comment by zagdrath** [comment]
The parameters for the SwerveDriveOdometry constructor have changed.

**Comment by dirtbikerxz** [comment]
Just Updated to 2023 WPILib (and added some features). 
Note: Haven't had a chance to actually test the WPILib changes from 22 to 23 on an actual robot yet, will test later this week and make sure nothing is broken.
